Fix travis-ci builds (#842)
* Update .travis.yml - try explicit emulator vars

Line 8 comment:
    system-images;android-25;android-tv;x86
    system-images;android-25;android-wear-cn;armeabi-v7a
    system-images;android-25;android-wear-cn;x86
    system-images;android-25;android-wear;armeabi-v7a
    system-images;android-25;android-wear;x86
    system-images;android-25;google_apis;arm64-v8a
    system-images;android-25;google_apis;armeabi-v7a
    system-images;android-25;google_apis;x86
    system-images;android-25;google_apis;x86_64
    system-images;android-25;google_apis_playstore;x86
    system-images;android-26;android-tv;x86
    system-images;android-26;android-wear-cn;x86
    system-images;android-26;android-wear;x86
    system-images;android-26;google_apis;x86
    system-images;android-26;google_apis;x86_64
    system-images;android-26;google_apis_playstore;x86
    system-images;android-27;android-tv;x86
    system-images;android-27;google_apis;x86
    system-images;android-27;google_apis_playstore;x86

* Use android create --package option

EMULATOR environment variable

* Emulator subprocess to attempt QT fix

Recursive file listing for debug info

* fix emulator, add gradle setup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,4 +1,22 @@
 language: android
+jdk: oraclejdk8
+sudo: false
+
+notifications:
+  email:
+    on_success: change
+    on_failure: change
+
+env:
+  global:
+    - COMPILE_API_LEVEL=27
+    - EMULATOR_API_LEVEL=24              # It seems emulator levels 25,26,27 from main repos have google_apis by default, and do not support armeabi-v7a. Check commit comment.
+    - EMULATOR_TAG=default               # Possible values are default, google_apis, android-tv, android-wear, android-wear-cn
+    - EMULATOR_ABI=armeabi-v7a           # Default is armeabi-v7a, possible options are: x86, x86_64, mips, arm64-v8a, armeabi-v7a. Note: check commit comment
+    - EMULATOR_NAME=qksms3
+    - ANDROID_BUILD_TOOLS_VERSION=27.0.2 # Match build-tools version used in build.gradle
+    - EMULATOR="system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_TAG};${EMULATOR_ABI}" # Used to install/create emulator
+
 android:
   components:
     - tools
@@ -7,14 +25,58 @@ android:
     - extra
 
     # The build tools used in the project
-    - build-tools-27.0.2
+    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
 
     # The SDK used in the project
-    - android-27
+    - android-${COMPILE_API_LEVEL}
 
+    # For running the emulator in Travis
+    - android-${EMULATOR_API_LEVEL}
+    - sys-img-${EMULATOR_ABI}-android-${EMULATOR_API_LEVEL}
+
+# Set up Android-sdk and the emulator
 before_install:
-  - yes | sdkmanager "platforms;android-27"
-  - echo no | android create avd --force -n test -t android-27 --abi armeabi-v7a
-  - emulator -avd test -no-audio -no-window &
+  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
+  - ls -lar $HOME/**/*
+
+  # List and delete unnecessary components to free space
+  - sdkmanager --list || true                                     # Print out package list for debug purposes
+  - sdkmanager --uninstall "extras;google;google_play_services"
+  - yes | sdkmanager "tools"                                      # Update tools
+  - yes | sdkmanager "platforms;android-${EMULATOR_API_LEVEL}"    # Android platform required by emulator
+  - yes | sdkmanager "platforms;android-${COMPILE_API_LEVEL}"     # Android platform required by compiler
+  - yes | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" # Android build tools
+  - yes | sdkmanager "${EMULATOR}" # Install emulator system image
+  - sdkmanager --list || true                                     # Print out package list for debug purposes
+
+# Run the emulator
+install:
+  # emulator instance
+  - echo no | android create avd --force -n ${EMULATOR_NAME} -k "${EMULATOR}"
+  # Run emulator in a subshell, this seems to solve the travis QT issue
+  - ( cd "$(dirname "$(which emulator)")" && ./emulator -avd ${EMULATOR_NAME} -verbose -show-kernel -selinux permissive -no-audio -no-window -no-boot-anim -wipe-data & )
   - android-wait-for-emulator
+  - adb shell settings put global window_animation_scale 0 &
+  - adb shell settings put global transition_animation_scale 0 &
+  - adb shell settings put global animator_duration_scale 0 &
+  - sleep 30
   - adb shell input keyevent 82 &
+  - adb devices
+
+# Gradle setup
+before_script:
+  - cd ${TRAVIS_BUILD_DIR}
+  - ./gradlew --version
+  - ./gradlew clean build
+
+# Build APK
+script:
+  - cd ${TRAVIS_BUILD_DIR}
+  - |
+    ./gradlew build assembleAndroidTest -PtestCoverageEnabled='true'
+    retval=$?
+    if [$retval -ne 0]; then
+      echo "error on assembling, exit code: "$retval
+      exit $retval
+    fi
+
